name: ir_remote_v3
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_bluetooth_serial: ^0.2.2
  qrscan: ^0.3.1
  shared_preferences: ^2.0.6
  flutter_layout_grid: ^1.0.1
  wifi: ^0.1.5
  ping_discover_network: ^0.2.0+1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  flutter_boost:
    git:
      url: https://github.com/aasirmutwalli22/flutter_boost.git


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
